---
title: "HUD"
author: "Lamar Foster"
date: "7/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Packages Used 
library(rio)
library(dplyr)
library(janitor)
library(tidyr)
library(stringr)
library(ggdist)
library(ggplot2)
library(tidy)
```

```{r}
# Import the HUD Data for 2010/11 to 2017
hud10_11 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2011f/fy2011_equiv_zc_rents_acs.xls")
hud12 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2012f/small_area_fmrs_fy2012.xls")
hud13 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2013p/small_area_fmrs_fy2013.xls")
hud14 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2014f/small_area_fmrs_fy2014.xls")
hud15 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2015f/small_area_fmrs_fy2015f.xls")
hud16 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2016f/final_fy2016_hypothetical_safmrs.xlsx")
hud17 <- import(file = "https://www.huduser.gov/portal/datasets/fmr/fmr2017/FY2017_hypothetical_safmrs.xlsx")
```

```{r}
# Make the variable names lowercase 
hud10_11 <- hud10_11 %>% clean_names()
hud15 <- hud15 %>% clean_names()
hud16 <- hud16 %>% clean_names()
hud17 <- hud17 %>% clean_names()

```

```{r}
#Combine hud 12-14
hud12 <- hud12 %>% 
  mutate(year = 2012)

hud13 <- hud13 %>% 
  mutate(year = 2013)

hud14 <- hud14 %>% 
  mutate(year = 2014)

hud12_14 <- bind_rows(hud12, hud13, hud14) %>% clean_names() %>% 
  select(-c(state, state_name, county))

```

```{r}
# Rename and cut/add variables
hud10_11 <- hud10_11 %>% 
  select(-c(state, county)) %>% 
rename(
cbsa = cbsamet) %>% 
  mutate(year = 2011)
```

```{r}
# Rename and cut/add variables
hud15 <- hud15 %>% 
  select(-c(state, statename, county)) %>% 
rename(
cbsa = cbsamet,
county_name = cntyname,
zip = zipcode,
cbsa_name = cbnsmcnm) %>% 
  mutate(year = 2015)
```

```{r}
# Rename and cut/add variables
hud16 <- hud16 %>% 
  select(-c(fips_state_code, fips_county_code, statename)) %>% 
rename(
cbsa = metro_code,
cbsa_name = metro_name,
zip = zip_code) %>% 
  mutate(year = 2016)
```

```{r}
# Rename and add variables
hud17 <- hud17 %>% 
rename(
cbsa = metro_code,
cbsa_name = metro_name,
zip = zip_code) %>% 
  mutate(year = 2017)
```

```{r}
# Combine the datasets 
hud_full <- plyr::rbind.fill(hud12_14, hud10_11, hud15, hud16, hud17)
```

```{r}
# Filter data for only Washington State 
hud_df <- hud_full %>% 
  separate(cbsa_name, into = c("city", "region"), sep = ",") %>%
  mutate(region = str_trim(region)) %>% 
  filter(region == "WA MSA") %>% 
  rename(
    region = city,
    state = region) %>%
  mutate(state = "WA")
```

```{r}
#Wrangle data to make it long
hud_long <- hud_df %>% 
  rename(
    county = county_name,
    Studio = area_rent_br0,
    `One Bedroom` = area_rent_br1,
    `Two Bedrooms` = area_rent_br2,
    `Three Bedrooms` = area_rent_br3,
    `Four Bedrooms` = area_rent_br4) %>% 
  pivot_longer(c(Studio, `One Bedroom`, `Two Bedrooms`, `Three Bedrooms`, `Four Bedrooms`), names_to = "Bedrooms", values_to = "Rent")
```

```{r}
# Make region and bedroom a factor with specific levels 
hud_long$Bedrooms <- factor(hud_long$Bedrooms, 
                         levels = c("Studio", "One Bedroom", "Two Bedrooms", "Three Bedrooms", "Four Bedrooms"))

hud_long$region <- factor(hud_long$region)
```

```{r}
hud_long %>%
    filter(region == "Seattle-Tacoma-Bellevue") %>% 
    ggplot(aes(x = factor(Bedrooms), y = Rent, fill = factor(Bedrooms))) +

    # add half-violin from {ggdist} package
    ggdist::stat_halfeye(
        ## custom bandwidth
        adjust = 0.5,
        ## move geom to the right
        justification = -.2,
        ## remove slab interval
        .width = 0,
        point_colour = NA
    ) +
    geom_boxplot(
        width = .12,
        ## remove outliers
        outlier.color = NA,
        alpha = 0.5
    ) +
    # Add dot plots from {ggdist} package
    ggdist::stat_dots(
        ## orientation to the left
        side = "left",
        ## move geom to the left
        justification = 1.1,
        ## adjust grouping (binning) of observations
        binwidth = .25
    ) +
    # Adjust theme
    scale_fill_tq() +
    theme_tq() +
    labs(
        title = "Distribution of Fair Market Housing in Washington State",
        subtitle = "For the Seattle-Tacoma-Bellevue Region",
        caption = "Data from Department of Housing and Urban Development",
        x = "Number of Bedrooms",
        y = "Rental Price",
        fill = "Bedrooms") +
  scale_y_discrete(limits = c(400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000, 3200, 3400)) +
    coord_flip() 
```


















